const students = require('./students/students.service.js')
const groups = require('./groups/groups.service.js')
const classSessions = require('./class-sessions/class-sessions.service.js')
const attendances = require('./attendances/attendances.service.js')
const points = require('./points/points.service.js')
const semesters = require('./semesters/semesters.service.js')
const viewers = require('./viewers/viewers.service.js')
const messages = require('./messages/messages.service.js')
const users = require('./users/users.service.js')
// eslint-disable-next-line no-unused-vars
module.exports = function (app) {
  app.configure(students)
  app.configure(groups)
  app.configure(classSessions)
  app.configure(attendances)
  app.configure(points)
  app.configure(semesters)
  app.configure(viewers)
  app.configure(messages)
  app.configure(users)
}
